CREATE TABLE tabela_campeao (
    id_campeao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL);

CREATE TABLE tabela_item (
    id_item NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_item VARCHAR2(50) NOT NULL);

CREATE TABLE tabela_runa (
    id_runa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_runa VARCHAR2(50) NOT NULL,
    caminho VARCHAR2(30) NOT NULL);

CREATE TABLE tabela_build (
    id_build NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_build VARCHAR2(50) NOT NULL,
    id_campeao NUMBER NOT NULL,
    FOREIGN KEY (id_campeao) REFERENCES tabela_campeao(id_campeao));

CREATE TABLE tabela_build_itens (
    id_build NUMBER NOT NULL,
    id_item NUMBER NOT NULL,
    PRIMARY KEY (id_build, id_item),
    FOREIGN KEY (id_build) REFERENCES tabela_build(id_build),
    FOREIGN KEY (id_item) REFERENCES tabela_item(id_item));

CREATE TABLE tabela_build_runas (
    id_build NUMBER NOT NULL,
    id_runa NUMBER NOT NULL,
    PRIMARY KEY (id_build, id_runa),
    FOREIGN KEY (id_build) REFERENCES tabela_build(id_build),
    FOREIGN KEY (id_runa) REFERENCES tabela_runa(id_runa));

-- Inserts -- 

-- Campeões
INSERT INTO tabela_campeao (nome) VALUES ('Ahri');
INSERT INTO tabela_campeao (nome) VALUES ('Lux');
INSERT INTO tabela_campeao (nome) VALUES ('Yone');

-- Itens
INSERT INTO tabela_item (nome_item) VALUES ('Luden');
INSERT INTO tabela_item (nome_item) VALUES ('Rabadon');
INSERT INTO tabela_item (nome_item) VALUES ('Gume do Infinito');

-- Runas
INSERT INTO tabela_runa (nome_runa, caminho) VALUES ('Eletrocutar', 'Dominação');
INSERT INTO tabela_runa (nome_runa, caminho) VALUES ('Cometa', 'Feitiçaria');
INSERT INTO tabela_runa (nome_runa, caminho) VALUES ('Conquistador', 'Precisão');

-- Builds
INSERT INTO tabela_build (nome_build, id_campeao) VALUES ('Ahri Burst', 1);
INSERT INTO tabela_build (nome_build, id_campeao) VALUES ('Lux Poke', 2);
INSERT INTO tabela_build (nome_build, id_campeao) VALUES ('Yasuo Critico', 3);

-- Itens por build
INSERT INTO tabela_build_itens VALUES (1, 1);
INSERT INTO tabela_build_itens VALUES (1, 2);

INSERT INTO tabela_build_itens VALUES (2, 1);
INSERT INTO tabela_build_itens VALUES (2, 2);

INSERT INTO tabela_build_itens VALUES (3, 3);

-- Runas por build
INSERT INTO tabela_build_runas VALUES (1, 1);
INSERT INTO tabela_build_runas VALUES (2, 2);
INSERT INTO tabela_build_runas VALUES (3, 3);
